sonar.projectKey=allanjeffersong_TaskForge---DevOps
sonar.organization=allanjeffersong
sonar.host.url=https://sonarcloud.io

# IGNORAR COBERTURA
sonar.coverage.exclusions=**git add sonar-project.properties