- name: Build e testes com cobertura
  run: |
    cd backend
    ./mvnw clean verify -DskipTests

- name: Análise SonarCloud
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: |
    cd backend
    ./mvnw sonar:sonar \
      -Dsonar.projectKey=allanjeffersong_TaskForge---DevOps \
      -Dsonar.organization=allanjeffersong \
      -Dsonar.host.url=https://sonarcloud.io \
      -DskipTests